# Generated by Django 6.0 on 2025-12-14 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
