# Generated by Django 5.2.7 on 2025-12-15 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
